use crate::catalog::{
    Loot, Rank, Resistances,
    effect::effect::Effect,
    heroes::{CombatMoveSkill, ExtraEconomy, HeroClass, HeroData, Mode, RiposteSkill, combat_skill::CombatSkill},
};

const HEROES: &[HeroData] = &[
    HeroData::new(
        HeroClass::Crusader,
        Resistances::new(40, 30, 30, 30, 40, 30, 67, 10),
        Effect::OnCritProt,
        [
            CombatSkill::Smite,
            CombatSkill::ZealousAccusation,
            CombatSkill::StunningBlow,
            CombatSkill::BulwarkOfFaith,
            CombatSkill::BattleHeal,
            CombatSkill::HolyLance,
            CombatSkill::InspiringCry,
        ],
        CombatMoveSkill::new(1, 1),
        RiposteSkill::new(0, 0),
        Rank::One,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Highwayman,
        Resistances::new(30, 30, 30, 30, 30, 30, 67, 40),
        Effect::OnCritSpeed,
        [
            CombatSkill::WickedSlice,
            CombatSkill::PistolShot,
            CombatSkill::PointBlankShot,
            CombatSkill::GrapeShotBlast,
            CombatSkill::TakeAim,
            CombatSkill::DuelistAdvance,
            CombatSkill::OpenedVein,
        ],
        CombatMoveSkill::new(2, 2),
        RiposteSkill::new(85, 50),
        Rank::One,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::PlagueDoctor,
        Resistances::new(20, 60, 20, 50, 20, 50, 67, 20),
        Effect::OnCritBlightChance,
        [
            CombatSkill::NoxiousBlast,
            CombatSkill::PlagueGrenade,
            CombatSkill::BlindingGas,
            CombatSkill::Incision,
            CombatSkill::BattlefieldMedicine,
            CombatSkill::EmboldeningVapours,
            CombatSkill::DisorientingBlast,
        ],
        CombatMoveSkill::new(1, 1),
        RiposteSkill::new(0, 0),
        Rank::Four,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Vestal,
        Resistances::new(30, 30, 40, 30, 30, 30, 67, 10),
        Effect::OnCritHealDone,
        [
            CombatSkill::MaceBash,
            CombatSkill::Judgement,
            CombatSkill::DazzlingLight,
            CombatSkill::DivineGrace,
            CombatSkill::GodsComfort,
            CombatSkill::GodsIllumination,
            CombatSkill::GodsHand,
        ],
        CombatMoveSkill::new(1, 1),
        RiposteSkill::new(0, 0),
        Rank::Four,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Hellion,
        Resistances::new(40, 40, 40, 30, 40, 30, 67, 20),
        Effect::OnCritDmgBleeding,
        [
            CombatSkill::WickedHack,
            CombatSkill::IronSwan,
            CombatSkill::BarbaricYawp,
            CombatSkill::IfItBleeds,
            CombatSkill::Breakthru,
            CombatSkill::AdrenalineRush,
            CombatSkill::BleedOut,
        ],
        CombatMoveSkill::new(0, 1),
        RiposteSkill::new(0, 0),
        Rank::One,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::BountyHunter,
        Resistances::new(40, 30, 30, 20, 40, 30, 67, 40),
        Effect::OnCritDmgMarked,
        [
            CombatSkill::CollectBounty,
            CombatSkill::TargetTag,
            CombatSkill::ComeHither,
            CombatSkill::Uppercut,
            CombatSkill::Flashbang,
            CombatSkill::FinishHim,
            CombatSkill::HookAndSlice,
        ],
        CombatMoveSkill::new(2, 2),
        RiposteSkill::new(85, 50),
        Rank::One,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::GraveRobber,
        Resistances::new(20, 50, 30, 30, 20, 30, 67, 50),
        Effect::OnCritDef,
        [
            CombatSkill::Pick,
            CombatSkill::Lunge,
            CombatSkill::FlashingDaggers,
            CombatSkill::ShadowFade,
            CombatSkill::ThrownDagger,
            CombatSkill::PoisonDart,
            CombatSkill::ToxinTrickery,
        ],
        CombatMoveSkill::new(2, 2),
        RiposteSkill::new(0, 0),
        Rank::Three,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Occultist,
        Resistances::new(20, 30, 40, 40, 20, 60, 67, 10),
        Effect::OnCritHealDone,
        [
            CombatSkill::Bloodlet,
            CombatSkill::AbyssalArtillery,
            CombatSkill::WeakeningCurse,
            CombatSkill::WyrdReconstruction,
            CombatSkill::DisruptiveCurse,
            CombatSkill::HandsFromAbyss,
            CombatSkill::DaemonsPull,
        ],
        CombatMoveSkill::new(2, 2),
        RiposteSkill::new(0, 0),
        Rank::Four,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Jester,
        Resistances::new(20, 40, 30, 20, 20, 40, 67, 30),
        Effect::OnCritStressHealDone,
        [
            CombatSkill::DirkStab,
            CombatSkill::Harvest,
            CombatSkill::HeroicEnd,
            CombatSkill::Solo,
            CombatSkill::SliceOff,
            CombatSkill::BattleBallad,
            CombatSkill::InspiringTune,
        ],
        CombatMoveSkill::new(3, 3),
        RiposteSkill::new(0, 0),
        Rank::Three,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Leper,
        Resistances::new(60, 40, 10, 20, 60, 40, 67, 10),
        Effect::OnCritAcc,
        [
            CombatSkill::Chop,
            CombatSkill::Hew,
            CombatSkill::Focus,
            CombatSkill::Revenge,
            CombatSkill::Withstand,
            CombatSkill::Solemnity,
            CombatSkill::Intimidate,
        ],
        CombatMoveSkill::new(0, 1),
        RiposteSkill::new(0, 0),
        Rank::One,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Arbalest,
        Resistances::new(40, 30, 30, 30, 40, 30, 67, 10),
        Effect::OnCritDmgMarked,
        [
            CombatSkill::SniperShot,
            CombatSkill::SuppressingFire,
            CombatSkill::SniperMark,
            CombatSkill::Bola,
            CombatSkill::Blindfire,
            CombatSkill::BattlefieldBandage,
            CombatSkill::Flare,
        ],
        CombatMoveSkill::new(2, 0),
        RiposteSkill::new(0, 0),
        Rank::One,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::ManAtArms,
        Resistances::new(40, 30, 40, 30, 40, 30, 67, 10),
        Effect::OnCritStressResist,
        [
            CombatSkill::Crush,
            CombatSkill::Rampart,
            CombatSkill::Bellow,
            CombatSkill::Defender,
            CombatSkill::Retribution,
            CombatSkill::Command,
            CombatSkill::Bolster,
        ],
        CombatMoveSkill::new(2, 2),
        RiposteSkill::new(90, 0),
        Rank::One,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Houndmaster,
        Resistances::new(40, 40, 40, 30, 40, 30, 67, 40),
        Effect::OnCritBleedChance,
        [
            CombatSkill::HoundsRush,
            CombatSkill::HoundsHarry,
            CombatSkill::Whistle,
            CombatSkill::Howl,
            CombatSkill::GuardDog,
            CombatSkill::LickWounds,
            CombatSkill::Blackjack,
        ],
        CombatMoveSkill::new(2, 2),
        RiposteSkill::new(0, 0),
        Rank::Four,
        4,
        &[Mode::Human],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Abomination,
        Resistances::new(40, 60, 30, 20, 40, 20, 67, 10),
        Effect::OnCritDmg,
        [
            CombatSkill::Transform,
            CombatSkill::Manacles,
            CombatSkill::Vomit,
            CombatSkill::Absolution,
            CombatSkill::Rake,
            CombatSkill::Rage,
            CombatSkill::Slam,
        ],
        CombatMoveSkill::new(2, 1),
        RiposteSkill::new(0, 0),
        Rank::Two,
        7,
        &[Mode::Human, Mode::Beast],
        ExtraEconomy::new(None, None, 0, 0),
    ),
    HeroData::new(
        HeroClass::Antiquarian,
        Resistances::new(20, 20, 20, 20, 20, 20, 67, 10),
        Effect::OnCritDef,
        [
            CombatSkill::KrisStab,
            CombatSkill::FesteringVapours,
            CombatSkill::Cower,
            CombatSkill::Flashpowder,
            CombatSkill::FortifyingVapours,
            CombatSkill::InvigoratingVapours,
            CombatSkill::ProtectMe,
        ],
        CombatMoveSkill::new(2, 2),
        RiposteSkill::new(0, 0),
        Rank::Four,
        4,
        &[Mode::Human],
        ExtraEconomy::new(Some(Loot::Antiq), Some(Loot::Antiq), 750, 15),
    ),
];
