use crate::catalog::{
    Loot, Rank, Resistances,
    effect::effect::Effect,
    heroes::{Armour, CombatMoveSkill, ExtraEconomy, HeroClass, HeroData, Mode, RiposteSkill, Weapon, combat_skill::CombatSkill},
};

const HEROES: &[HeroData] = &[
    HeroData::new(
        HeroClass::Crusader,
        Resistances::new(40, 30, 30, 30, 40, 30, 67, 10),
        Effect::OnCritProt,
        [
            Weapon::new((6, 12), 3, 1),
            Weapon::new((7, 14), 4, 1),
            Weapon::new((8, 16), 5, 2),
            Weapon::new((9, 17), 6, 2),
            Weapon::new((10, 19), 7, 3),
        ],
        [
            Armour::new(50, 33),
            Armour::new(100, 40),
            Armour::new(150, 47),
            Armour::new(200, 54),
            Armour::new(250, 61),
        ],
        [
            CombatSkill::Smite,
            CombatSkill::ZealousAccusation,
            CombatSkill::StunningBlow,
            CombatSkill::BulwarkOfFaith,
            CombatSkill::BattleHeal,
            CombatSkill::HolyLance,
            CombatSkill::InspiringCry,
        ],
        CombatMoveSkill::new(1, 1),
        Rank::One,
        4,
    ),
    HeroData::new(
        HeroClass::Highwayman,
        Resistances::new(30, 30, 30, 30, 30, 30, 67, 40),
        Effect::OnCritSpeed,
        [
            Weapon::new((5, 10), 5, 5),
            Weapon::new((6, 12), 6, 5),
            Weapon::new((7, 13), 7, 6),
            Weapon::new((8, 15), 8, 6),
            Weapon::new((9, 16), 9, 7),
        ],
        [
            Armour::new(100, 23),
            Armour::new(150, 28),
            Armour::new(200, 33),
            Armour::new(250, 38),
            Armour::new(300, 43),
        ],
        [
            CombatSkill::WickedSlice,
            CombatSkill::PistolShot,
            CombatSkill::PointBlankShot,
            CombatSkill::GrapeShotBlast,
            CombatSkill::TakeAim,
            CombatSkill::DuelistAdvance,
            CombatSkill::OpenedVein,
        ],
        CombatMoveSkill::new(2, 2),
        Rank::One,
        4,
    )
    .with_riposte(RiposteSkill::new(85, 50)),
    HeroData::new(
        HeroClass::PlagueDoctor,
        Resistances::new(20, 60, 20, 50, 20, 50, 67, 20),
        Effect::OnCritBlightChance,
        [
            Weapon::new((4, 7), 2, 7),
            Weapon::new((5, 8), 3, 7),
            Weapon::new((6, 10), 4, 8),
            Weapon::new((6, 11), 5, 8),
            Weapon::new((7, 13), 6, 9),
        ],
        [
            Armour::new(0, 22),
            Armour::new(50, 26),
            Armour::new(100, 30),
            Armour::new(150, 34),
            Armour::new(200, 38),
        ],
        [
            CombatSkill::NoxiousBlast,
            CombatSkill::PlagueGrenade,
            CombatSkill::BlindingGas,
            CombatSkill::Incision,
            CombatSkill::BattlefieldMedicine,
            CombatSkill::EmboldeningVapours,
            CombatSkill::DisorientingBlast,
        ],
        CombatMoveSkill::new(1, 1),
        Rank::Four,
        4,
    ),
    HeroData::new(
        HeroClass::Vestal,
        Resistances::new(30, 30, 40, 30, 30, 30, 67, 10),
        Effect::OnCritHealDone,
        [
            Weapon::new((4, 8), 1, 4),
            Weapon::new((5, 10), 2, 4),
            Weapon::new((6, 11), 3, 5),
            Weapon::new((6, 13), 4, 5),
            Weapon::new((7, 14), 5, 6),
        ],
        [
            Armour::new(0, 24),
            Armour::new(50, 29),
            Armour::new(100, 34),
            Armour::new(150, 39),
            Armour::new(200, 44),
        ],
        [
            CombatSkill::MaceBash,
            CombatSkill::Judgement,
            CombatSkill::DazzlingLight,
            CombatSkill::DivineGrace,
            CombatSkill::GodsComfort,
            CombatSkill::GodsIllumination,
            CombatSkill::GodsHand,
        ],
        CombatMoveSkill::new(1, 1),
        Rank::Four,
        4,
    ),
    HeroData::new(
        HeroClass::Hellion,
        Resistances::new(40, 40, 40, 30, 40, 30, 67, 20),
        Effect::OnCritDmgBleeding,
        [
            Weapon::new((6, 12), 5, 4),
            Weapon::new((7, 14), 6, 4),
            Weapon::new((8, 16), 7, 5),
            Weapon::new((9, 17), 8, 5),
            Weapon::new((10, 19), 9, 6),
        ],
        [
            Armour::new(100, 26),
            Armour::new(150, 31),
            Armour::new(200, 36),
            Armour::new(250, 41),
            Armour::new(300, 46),
        ],
        [
            CombatSkill::WickedHack,
            CombatSkill::IronSwan,
            CombatSkill::BarbaricYawp,
            CombatSkill::IfItBleeds,
            CombatSkill::Breakthru,
            CombatSkill::AdrenalineRush,
            CombatSkill::BleedOut,
        ],
        CombatMoveSkill::new(0, 1),
        Rank::One,
        4,
    ),
    HeroData::new(
        HeroClass::BountyHunter,
        Resistances::new(40, 30, 30, 20, 40, 30, 67, 40),
        Effect::OnCritDmgMarked,
        [
            Weapon::new((5, 10), 4, 5),
            Weapon::new((6, 12), 5, 5),
            Weapon::new((7, 13), 6, 6),
            Weapon::new((7, 15), 7, 6),
            Weapon::new((8, 16), 8, 7),
        ],
        [
            Armour::new(50, 25),
            Armour::new(100, 30),
            Armour::new(150, 35),
            Armour::new(200, 40),
            Armour::new(250, 45),
        ],
        [
            CombatSkill::CollectBounty,
            CombatSkill::TargetTag,
            CombatSkill::ComeHither,
            CombatSkill::Uppercut,
            CombatSkill::Flashbang,
            CombatSkill::FinishHim,
            CombatSkill::HookAndSlice,
        ],
        CombatMoveSkill::new(2, 2),
        Rank::One,
        4,
    )
    .with_riposte(RiposteSkill::new(85, 50)),
    HeroData::new(
        HeroClass::GraveRobber,
        Resistances::new(20, 50, 30, 30, 20, 30, 67, 50),
        Effect::OnCritDef,
        [
            Weapon::new((4, 8), 6, 8),
            Weapon::new((5, 10), 7, 8),
            Weapon::new((6, 11), 8, 9),
            Weapon::new((6, 13), 9, 9),
            Weapon::new((7, 14), 10, 10),
        ],
        [
            Armour::new(100, 20),
            Armour::new(150, 24),
            Armour::new(200, 28),
            Armour::new(250, 32),
            Armour::new(300, 36),
        ],
        [
            CombatSkill::Pick,
            CombatSkill::Lunge,
            CombatSkill::FlashingDaggers,
            CombatSkill::ShadowFade,
            CombatSkill::ThrownDagger,
            CombatSkill::PoisonDart,
            CombatSkill::ToxinTrickery,
        ],
        CombatMoveSkill::new(2, 2),
        Rank::Three,
        4,
    ),
    HeroData::new(
        HeroClass::Occultist,
        Resistances::new(20, 30, 40, 40, 20, 60, 67, 10),
        Effect::OnCritHealDone,
        [
            Weapon::new((4, 7), 6, 6),
            Weapon::new((5, 8), 7, 7),
            Weapon::new((6, 10), 8, 7),
            Weapon::new((6, 11), 9, 7),
            Weapon::new((7, 13), 10, 8),
        ],
        [
            Armour::new(100, 19),
            Armour::new(150, 23),
            Armour::new(200, 27),
            Armour::new(250, 31),
            Armour::new(300, 35),
        ],
        [
            CombatSkill::Bloodlet,
            CombatSkill::AbyssalArtillery,
            CombatSkill::WeakeningCurse,
            CombatSkill::WyrdReconstruction,
            CombatSkill::DisruptiveCurse,
            CombatSkill::HandsFromAbyss,
            CombatSkill::DaemonsPull,
        ],
        CombatMoveSkill::new(2, 2),
        Rank::Four,
        4,
    ),
    HeroData::new(
        HeroClass::Jester,
        Resistances::new(20, 40, 30, 20, 20, 40, 67, 30),
        Effect::OnCritStressHealDone,
        [
            Weapon::new((4, 7), 4, 7),
            Weapon::new((5, 8), 5, 7),
            Weapon::new((6, 10), 6, 8),
            Weapon::new((6, 11), 7, 8),
            Weapon::new((7, 13), 8, 9),
        ],
        [
            Armour::new(150, 19),
            Armour::new(200, 23),
            Armour::new(250, 27),
            Armour::new(300, 31),
            Armour::new(350, 35),
        ],
        [
            CombatSkill::DirkStab,
            CombatSkill::Harvest,
            CombatSkill::HeroicEnd,
            CombatSkill::Solo,
            CombatSkill::SliceOff,
            CombatSkill::BattleBallad,
            CombatSkill::InspiringTune,
        ],
        CombatMoveSkill::new(3, 3),
        Rank::Three,
        4,
    ),
    HeroData::new(
        HeroClass::Leper,
        Resistances::new(60, 40, 10, 20, 60, 40, 67, 10),
        Effect::OnCritAcc,
        [
            Weapon::new((8, 16), 1, 2),
            Weapon::new((9, 18), 2, 2),
            Weapon::new((10, 21), 3, 3),
            Weapon::new((12, 23), 4, 3),
            Weapon::new((13, 26), 5, 4),
        ],
        [
            Armour::new(0, 35),
            Armour::new(50, 42),
            Armour::new(100, 49),
            Armour::new(150, 56),
            Armour::new(200, 63),
        ],
        [
            CombatSkill::Chop,
            CombatSkill::Hew,
            CombatSkill::Focus,
            CombatSkill::Revenge,
            CombatSkill::Withstand,
            CombatSkill::Solemnity,
            CombatSkill::Intimidate,
        ],
        CombatMoveSkill::new(0, 1),
        Rank::One,
        4,
    ),
    HeroData::new(
        HeroClass::Arbalest,
        Resistances::new(40, 30, 30, 30, 40, 30, 67, 10),
        Effect::OnCritDmgMarked,
        [
            Weapon::new((4, 8), 6, 3),
            Weapon::new((5, 10), 7, 3),
            Weapon::new((6, 11), 8, 4),
            Weapon::new((6, 13), 9, 4),
            Weapon::new((7, 14), 10, 5),
        ],
        [
            Armour::new(0, 27),
            Armour::new(50, 32),
            Armour::new(100, 37),
            Armour::new(150, 42),
            Armour::new(200, 47),
        ],
        [
            CombatSkill::SniperShot,
            CombatSkill::SuppressingFire,
            CombatSkill::SniperMark,
            CombatSkill::Bola,
            CombatSkill::Blindfire,
            CombatSkill::BattlefieldBandage,
            CombatSkill::Flare,
        ],
        CombatMoveSkill::new(2, 0),
        Rank::One,
        4,
    ),
    HeroData::new(
        HeroClass::ManAtArms,
        Resistances::new(40, 30, 40, 30, 40, 30, 67, 10),
        Effect::OnCritStressResist,
        [
            Weapon::new((5, 9), 2, 3),
            Weapon::new((6, 10), 3, 3),
            Weapon::new((7, 12), 4, 4),
            Weapon::new((7, 13), 5, 4),
            Weapon::new((8, 14), 6, 5),
        ],
        [
            Armour::new(50, 31),
            Armour::new(100, 37),
            Armour::new(150, 43),
            Armour::new(200, 49),
            Armour::new(250, 55),
        ],
        [
            CombatSkill::Crush,
            CombatSkill::Rampart,
            CombatSkill::Bellow,
            CombatSkill::Defender,
            CombatSkill::Retribution,
            CombatSkill::Command,
            CombatSkill::Bolster,
        ],
        CombatMoveSkill::new(2, 2),
        Rank::One,
        4,
    )
    .with_riposte(RiposteSkill::new(90, 0)),
    HeroData::new(
        HeroClass::Houndmaster,
        Resistances::new(40, 40, 40, 30, 40, 30, 67, 40),
        Effect::OnCritBleedChance,
        [
            Weapon::new((4, 7), 4, 5),
            Weapon::new((5, 8), 5, 5),
            Weapon::new((6, 10), 6, 6),
            Weapon::new((6, 11), 7, 6),
            Weapon::new((7, 13), 8, 7),
        ],
        [
            Armour::new(100, 21),
            Armour::new(150, 25),
            Armour::new(200, 29),
            Armour::new(250, 33),
            Armour::new(300, 37),
        ],
        [
            CombatSkill::HoundsRush,
            CombatSkill::HoundsHarry,
            CombatSkill::Whistle,
            CombatSkill::Howl,
            CombatSkill::GuardDog,
            CombatSkill::LickWounds,
            CombatSkill::Blackjack,
        ],
        CombatMoveSkill::new(2, 2),
        Rank::Four,
        4,
    ),
    HeroData::new(
        HeroClass::Abomination,
        Resistances::new(40, 60, 30, 20, 40, 20, 67, 10),
        Effect::OnCritDmg,
        [
            Weapon::new((6, 11), 2, 7),
            Weapon::new((7, 13), 3, 7),
            Weapon::new((8, 15), 4, 8),
            Weapon::new((10, 18), 5, 8),
            Weapon::new((11, 20), 6, 9),
        ],
        [
            Armour::new(75, 26),
            Armour::new(125, 31),
            Armour::new(175, 36),
            Armour::new(225, 41),
            Armour::new(275, 46),
        ],
        [
            CombatSkill::Transform,
            CombatSkill::Manacles,
            CombatSkill::Vomit,
            CombatSkill::Absolution,
            CombatSkill::Rake,
            CombatSkill::Rage,
            CombatSkill::Slam,
        ],
        CombatMoveSkill::new(2, 1),
        Rank::Two,
        7,
    )
    .with_modes(&[Mode::Human, Mode::Beast]),
    HeroData::new(
        HeroClass::Antiquarian,
        Resistances::new(20, 20, 20, 20, 20, 20, 67, 10),
        Effect::OnCritDef,
        [
            Weapon::new((3, 5), 1, 5),
            Weapon::new((4, 6), 2, 5),
            Weapon::new((4, 7), 3, 6),
            Weapon::new((5, 8), 4, 6),
            Weapon::new((5, 9), 5, 7),
        ],
        [
            Armour::new(100, 17),
            Armour::new(150, 20),
            Armour::new(200, 23),
            Armour::new(250, 26),
            Armour::new(300, 29),
        ],
        [
            CombatSkill::KrisStab,
            CombatSkill::FesteringVapours,
            CombatSkill::Cower,
            CombatSkill::Flashpowder,
            CombatSkill::FortifyingVapours,
            CombatSkill::InvigoratingVapours,
            CombatSkill::ProtectMe,
        ],
        CombatMoveSkill::new(2, 2),
        Rank::Four,
        4,
    )
    .with_extra_economy(ExtraEconomy::new(Some(Loot::Antiq), Some(Loot::Antiq), 750, 15)),
];
